/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/experts/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the authenticated expert profile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Expert profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ExpertProfile"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the authenticated expert profile */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ExpertProfileUpdateInput"];
        };
      };
      responses: {
        /** @description Updated expert profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ExpertProfile"];
          };
        };
      };
    };
    trace?: never;
  };
  "/experts/me/opportunities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List opportunities for the authenticated expert */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Opportunity summaries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OpportunitySummary"][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/opportunities/{opportunityId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get opportunity detail */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          opportunityId: components["parameters"]["OpportunityId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Opportunity detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OpportunityDetail"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/opportunities/{opportunityId}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept an opportunity */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          opportunityId: components["parameters"]["OpportunityId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Updated opportunity summary */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OpportunitySummary"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/opportunities/{opportunityId}/decline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Decline an opportunity */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          opportunityId: components["parameters"]["OpportunityId"];
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            reason?: string;
          };
        };
      };
      responses: {
        /** @description Updated opportunity summary */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OpportunitySummary"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/opportunities/{opportunityId}/screening-answers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit screening answers */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          opportunityId: components["parameters"]["OpportunityId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            answers: components["schemas"]["ScreeningAnswerInput"][];
            /** @default false */
            submit?: boolean;
          };
        };
      };
      responses: {
        /** @description Submitted answers */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ScreeningAnswer"][];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/availability-rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List availability rules */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Availability rules */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AvailabilityRule"][];
          };
        };
      };
    };
    put?: never;
    /** Create availability rule */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AvailabilityRuleInput"];
        };
      };
      responses: {
        /** @description Created availability rule */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AvailabilityRule"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    /** Update availability rule */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AvailabilityRuleInput"] & {
            /** Format: uuid */
            id: string;
          };
        };
      };
      responses: {
        /** @description Updated availability rule */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AvailabilityRule"];
          };
        };
      };
    };
    trace?: never;
  };
  "/bookings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List bookings for the authenticated expert */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Booking list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Booking"][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bookings/{bookingId}/ics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Export a booking as an ICS calendar entry */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          bookingId: components["parameters"]["BookingId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Generated ICS content */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/calendar": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/compliance/attestations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List compliance attestations */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Attestations */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ComplianceAttestation"][];
          };
        };
      };
    };
    put?: never;
    /** Complete a compliance attestation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            ruleId: string;
            accepted: boolean;
          };
        };
      };
      responses: {
        /** @description Created attestation */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ComplianceAttestation"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List payment records */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Payment records */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PaymentRecord"][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payments/{engagementId}/external-link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate a secure external payment link */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          engagementId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description External payment link */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uri */
              url: string;
              /** Format: date-time */
              expiresAt: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ops/opportunities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an opportunity */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["OpportunityInput"];
        };
      };
      responses: {
        /** @description Created opportunity */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OpportunityDetail"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    /** Update an opportunity */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["OpportunityInput"] & {
            /** Format: uuid */
            id: string;
          };
        };
      };
      responses: {
        /** @description Updated opportunity */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OpportunityDetail"];
          };
        };
      };
    };
    trace?: never;
  };
  "/ops/opportunities/{opportunityId}/candidates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add expert candidates to an opportunity */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          opportunityId: components["parameters"]["OpportunityId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            expertIds: string[];
          };
        };
      };
      responses: {
        /** @description Updated candidate list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uuid */
              opportunityId: string;
              expertIds: string[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ops/verification/{expertId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update verification state for an expert */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          expertId: components["parameters"]["ExpertId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            status: components["schemas"]["VerificationStatus"];
            reason?: string;
          };
        };
      };
      responses: {
        /** @description Updated verification summary */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["VerificationSummary"];
          };
        };
      };
    };
    trace?: never;
  };
  "/ops/compliance-rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a compliance rule */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ComplianceRuleInput"];
        };
      };
      responses: {
        /** @description Created rule */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ComplianceRule"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    /** Update a compliance rule */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ComplianceRuleInput"] & {
            /** Format: uuid */
            id: string;
          };
        };
      };
      responses: {
        /** @description Updated rule */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ComplianceRule"];
          };
        };
      };
    };
    trace?: never;
  };
  "/ops/payments/{paymentId}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update payment status */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          paymentId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            status: components["schemas"]["PaymentStatus"];
            note?: string;
          };
        };
      };
      responses: {
        /** @description Updated payment record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PaymentRecord"];
          };
        };
      };
    };
    trace?: never;
  };
  "/ops/audit-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit events */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Audit events */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuditEvent"][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    ExpertStatus:
      | "active"
      | "pending_verification"
      | "restricted"
      | "suspended";
    /** @enum {string} */
    VerificationStatus:
      | "not_started"
      | "pending"
      | "completed"
      | "failed"
      | "expired";
    /** @enum {string} */
    BookingStatus:
      | "proposed"
      | "scheduled"
      | "completed"
      | "cancelled"
      | "no_show";
    /** @enum {string} */
    PaymentStatus:
      | "not_eligible"
      | "pending_request"
      | "requested_external"
      | "submitted"
      | "approved"
      | "paid"
      | "held";
    /** @enum {string} */
    OpportunityStatus:
      | "invited"
      | "screening_in_progress"
      | "accepted"
      | "declined"
      | "slot_proposed"
      | "scheduled"
      | "completed"
      | "payment_pending"
      | "paid"
      | "held";
    VerificationSummary: {
      status: components["schemas"]["VerificationStatus"];
      personaInquiryId: string;
      /** Format: date-time */
      updatedAt: string;
      outcomeSummary?: string;
    };
    ExpertProfile: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      status: components["schemas"]["ExpertStatus"];
      verification: components["schemas"]["VerificationSummary"];
      fullName: string;
      headline: string;
      timezone: string;
      expertiseTags: string[];
      roleHistory: components["schemas"]["RoleHistoryItem"][];
      recencySignals: components["schemas"]["RecencySignal"][];
      /** Format: date-time */
      lastConfirmedAt: string;
    };
    ExpertProfileUpdateInput: {
      fullName?: string;
      headline?: string;
      timezone?: string;
      expertiseTags?: string[];
    };
    RoleHistoryItem: {
      company: string;
      title: string;
      /** Format: date */
      startedAt: string;
      /** Format: date */
      endedAt?: string;
    };
    RecencySignal: {
      /** Format: uuid */
      id: string;
      topic: string;
      /** Format: date */
      lastHandsOnDate: string;
      confidence: number;
      source: string;
    };
    ScreeningQuestion: {
      /** Format: uuid */
      id: string;
      prompt: string;
      required: boolean;
    };
    ScreeningAnswerInput: {
      /** Format: uuid */
      questionId: string;
      answerText: string;
    };
    ScreeningAnswer: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      questionId: string;
      answerText: string;
      /** Format: date-time */
      submittedAt: string;
      version: number;
    };
    OpportunitySummary: {
      /** Format: uuid */
      id: string;
      title: string;
      topic: string;
      status: components["schemas"]["OpportunityStatus"];
      /** Format: date-time */
      deadlineAt: string;
      rateUsd: number;
      complianceFlags: string[];
    };
    OpportunityDetail: components["schemas"]["OpportunitySummary"] & {
      description: string;
      estimatedMinutes: number;
      screeningQuestions: components["schemas"]["ScreeningQuestion"][];
    };
    OpportunityInput: {
      title: string;
      topic: string;
      /** Format: date-time */
      deadlineAt: string;
      description: string;
      estimatedMinutes: number;
      rateUsd: number;
    };
    AvailabilityRule: {
      /** Format: uuid */
      id: string;
      timezone: string;
      weekday: number;
      startTime: string;
      endTime: string;
      leadHours: number;
      blackoutDates: string[];
    };
    AvailabilityRuleInput: {
      timezone: string;
      weekday: number;
      startTime: string;
      endTime: string;
      leadHours: number;
      blackoutDates?: string[];
    };
    Booking: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      opportunityId: string;
      /** Format: uuid */
      expertId: string;
      title: string;
      /** Format: date-time */
      startAt: string;
      /** Format: date-time */
      endAt: string;
      status: components["schemas"]["BookingStatus"];
      timezone: string;
    };
    ComplianceRule: {
      /** Format: uuid */
      id: string;
      name: string;
      ruleType: string;
      description: string;
      blocking: boolean;
    };
    ComplianceRuleInput: {
      name: string;
      ruleType: string;
      description: string;
      blocking: boolean;
    };
    ComplianceAttestation: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      ruleId: string;
      accepted: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    PaymentRecord: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      engagementId: string;
      status: components["schemas"]["PaymentStatus"];
      amountUsd: number;
      /** Format: date-time */
      dueAt: string;
      payoutLinkIssued: boolean;
    };
    AuditEvent: {
      /** Format: uuid */
      id: string;
      actorType: string;
      /** Format: uuid */
      actorId: string;
      action: string;
      entityType: string;
      /** Format: uuid */
      entityId: string;
      payload: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt: string;
    };
  };
  responses: never;
  parameters: {
    OpportunityId: string;
    BookingId: string;
    ExpertId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
